### ISSUE TITLE
Moving dbConnectionString to be a protocol

### ISSUE THREAD

**Issue by zelcion** [mapikit/meta-system#67]
## Description
On Meta-System, you are required to specify a MongoDB connection string whenever using schemas. The way this current module is structure makes evident the lack of flexibility of the module. We simply cannot use other databases than MongoDB.

Now, given that for 0.2 the protocols have received a "power up", we can leverage on that same structure and introduce "DBProtocols". They would be protocols but for accessing the Database, and interacting with Schemas.

With this, without any change to the schemas or any other part of the configuration, we should be able to use any different form of data persistence/caching. We could, for instance, have a DBProtocol that stores data in memory, and another that writes into a Redis.

## Solving Suggestion
The plan would be to use the same structure built for v0.2 for the protocols. This means the DBProtocols should:
- Be Downloadable through NPM
- Have a verifiable interface
- Just like other pluggable parts of Meta-System, Have a library for helping develop them.

Also this would mean we would have to extract the current drivers for MongoDB from the core into a separate library, which sounds like an architectural improvement to me.

**Comment by 0dp** [comment]
maybe add `.env` to hold
```
DB_DRIVER= / DBProtocol=
DB_HOST=
DB_NAME=
DB_USER=
DB_PASS=
DB_PORT=
DB_CHARSET=
```

or would it be preferred to expand on the existing way in config ie.
```
"dbConnection": {
    "driver": ,
    "host":,
    "name":,
    "password":,
    "port":,
    "charset":,
}
```
