### ISSUE TITLE
Introduce Configuration File Splitting in System Configuration

### ISSUE THREAD

**Issue by zelcion** [mapikit/meta-system#69]
## Description
For medium to big systems, the configuration file size can become quite the challenge to manage, given that all the system configuration must be contained in a single file.

## Solving Suggestion
The user should be able to define BOps and protocols configurations in separate files, since they tend to be the largest part of a system configuration, and are independent from one another.

The file break should be indicated having a file path string present in the place of the object.
```jsonc
{
  "businessOperations": [
    { /*bops1*/ },
    "/path/to/bops2",
    { /*bops3*/ },
   // And so on
  ]
}
```
A couple of rules should apply:
- The file path can be relative or absolute.
- Failing to find such file means the System will fail to boot.
- As the example above, not every business operation/protocol configuration needs to be split into different files.

**Comment by 0dp** [comment]
From openAPI specs:
```
paths:
  /pets/{petId}:
    get:
      summary: Info for a specific pet
      operationId: showPetById
      parameters:
        - $ref: '#/components/parameters/petId'
```

Here we are not only able spilt the scheme into smaller files via `$ref` we can also pass parameters `petId` to the referenced file.
