### ISSUE TITLE
Missing page

### ISSUE THREAD

**Issue by 0dp** [mapikit/meta-system#70]
Missing url `https://mapikit.github.io/meta-system-docs/docs/api-docs/getting-started/configuring/basics`

Linked from last paragraph here
`https://mapikit.github.io/meta-system-docs/docs/api-docs/getting-started/`

**Comment by zelcion** [comment]
Hey, nice catch! Just fixed this broken link :+1: 

If it does not work for you yet, perhaps the page is cached, try in a incognito window and you should be good to go.
