### ISSUE TITLE
Missing pages in doc

### ISSUE THREAD

**Issue by 0dp** [mapikit/meta-system#71]
Hi again,

https://mapikit.github.io/meta-system-docs/docs/api-docs/configuring/basics/

All section links are missing

**Comment by zelcion** [comment]
Thank you, fixed once again.

It appears to be some inconsistent behavior while referencing the markdown files... some links works with just the path, while others I need to use `.md` at the end.

Please keep opening issues if you find more broken links, or even better, you can drop a message at our [discord](https://discord.gg/ndGsnbTW7V).

**Comment by 0dp** [comment]
I'll join the discord for sure
